### ISSUE TITLE
wrong number of arguments

### ISSUE THREAD

**Issue by vladbondarenko97** [kirbs-/sensi#2]
```
/var/lib/gems/2.1.0/gems/sensi-0.1.2/lib/sensi/thermostat.rb:213:in `system_temperature': wrong number of arguments (1 for 0) (ArgumentError)
        from sensi.rb:19:in `<main>'
```

This happens when I attempt to `thermostat.system_temperature :cool`.

**Comment by kirbs-** [comment]
Try `thermostat.system_temperature type: :cool`

Edit: typo

**Comment by vladbondarenko97** [comment]
Thank you for responding, it works!

**Comment by kirbs-** [comment]
No problem. The documentation needs updating and I've been putting it off.
